name: "Ha Wake Word"
version: "1.0"
slug: "ha_wake_word"
description: "Wake word detection with openWakeWord"
arch: ["armhf", "armv7", "aarch64"]  # Matches Raspberry Pi models
startup: "application"
boot: "auto"
host_network: true  # Needed for UDP
options:
  ha_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2Y2JhMTA3MDJmZWQ0MGZiODI4NjcwYzc1NTY0NDQ4MCIsImlhdCI6MTc0MTk0MTgzMSwiZXhwIjoyMDU3MzAxODMxfQ.kxjltctUJmoPEY1UrUIjsbtz8Q_RhurhkjV9MqIVlQg"  # Replace with your HA token
  port: 5000
schema:
  ha_token: "str"
  port: "int"
